### ISSUE TITLE
ASR outputs "v" instead of "ث"

### ISSUE THREAD

**Issue by FarisHijazi** [ARBML/klaam#15]
I'm not sure where the problem occurs exactly, but this is the only letter, ث is always "v"

Perhaps check the vocabulary files

**Comment by zaidalyafeai** [comment]
Can't recreate that, do you have an example?

**Comment by FarisHijazi** [comment]
just tried it now and ث is correct, this is a new machine and a new installation though, I lost access to the older machine, lemme see if I can get a sample to reproduce this. (might take some time)
