### ISSUE TITLE
 assert batch_size * group_size < len(dataset) AssertionError when I train the model 

### ISSUE THREAD

**Issue by zaynabmu** [ARBML/klaam#22]
hello everyone, 

@zaidalyafeai @mustafa0x @elgeish @MagedSaeed 

I tried to train the model  in my dataset and this error comes out could you please help me this is Traceback (most recent call last):
  File "/content/drive/MyDrive/FastSpeech2/train.py", line 198, in <module>
    main(args, configs)
  File "/content/drive/MyDrive/FastSpeech2/train.py", line 32, in main
    assert batch_size * group_size < len(dataset)
AssertionError

thank you

**Comment by zaidalyafeai** [comment]
maybe try smaller `batch_size` ?

**Comment by zaidalyafeai** [comment]
closed for no answer from the op.
