### ISSUE TITLE
Speech Recognition Error

### ISSUE THREAD

**Issue by waleedahmed2090** [ARBML/klaam#26]
Speech Recognition

OSError: Can't load config for 'Zaid/wav2vec2-large-xlsr-dialect-classification'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Zaid/wav2vec2-large-xlsr-dialect-classification' is the correct path to a directory containing a config.json file

**Comment by zaidalyafeai** [comment]
We changed the path to `arbml/wav2vec2-large-xlsr-dialect-classification`, would you like to create a PR to fix this?

**Comment by zaidalyafeai** [comment]
fixed.
