### ISSUE TITLE
No such file or directory: 'model.pth.tar' when create TextToSpeech instance

### ISSUE THREAD

**Issue by ElsebaiyMohamed** [ARBML/klaam#33]
i'm testing  Demo Nootbook and i faced this error when creating an instance of TextToSpeech  model 

---

![image](https://user-images.githubusercontent.com/77920008/220698472-b5ebc0be-593b-4843-8820-07f3832fb40d.png)

**Comment by radicali94** [comment]
Indeed, model.pth.tar is no longer hosted in google drive.

**Comment by zaidalyafeai** [comment]
Unfortunately, the model was deleted by mistake from my drive. I don't have any copy of it locally. If someone has downloaded it before they can reupload it.

**Comment by paulaehab** [comment]
Can you check the history in Google Drive or the recycle bin as I need the library to be work soon

**Comment by zaidalyafeai** [comment]
> Can you check the history in Google Drive or the recycle bin as I need the library to be work soon

Even the bin is empty.

**Comment by zaidalyafeai** [comment]
The model can be retrained easily in google colab by follwing https://github.com/ARBML/klaam#text-to-speech-1

**Comment by radicali94** [comment]
The training files need some minor tweaks to work. I am currently training the model. Once the training is complete, I will try to make it available again.
![training](https://user-images.githubusercontent.com/36280408/222205444-f8253937-c60b-49d9-a3f1-e891811e53ac.png)

**Comment by zaidalyafeai** [comment]
> The training files need some minor tweaks to work. I am currently training the model. Once the training is complete, I will try to make it available again. ![training](https://user-images.githubusercontent.com/36280408/222205444-f8253937-c60b-49d9-a3f1-e891811e53ac.png)
Awesome, thanks!

**Comment by ElsebaiyMohamed** [comment]
> Wating you to finish it 🔥 
 @radicali94

**Comment by paulaehab** [comment]
> The training files need some minor tweaks to work. I am currently training the model. Once the training is complete, I will try to make it available again. ![training](https://user-images.githubusercontent.com/36280408/222205444-f8253937-c60b-49d9-a3f1-e891811e53ac.png)

Waiting you to finish after you finish, please let us know

**Comment by beatthem** [comment]
> The training files need some minor tweaks to work. I am currently training the model. Once the training is complete, I will try to make it available again. ![training](https://user-images.githubusercontent.com/36280408/222205444-f8253937-c60b-49d9-a3f1-e891811e53ac.png)

Did you train the model? Thanks in advance

**Comment by nipponjo** [comment]
I downloaded the file a while ago and have uploaded it again now. Here is the [link](https://drive.google.com/u/0/uc?id=1cN-1fWlBpHQONfz2kwHiw-25lz39Sw7M&export=download).

**Comment by zaidalyafeai** [comment]
Thank you @nipponjo, updated the drive link.
