### ISSUE TITLE
Text to Speech 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/klaam#4]
We are thinking to add TTS models, here are some possible architectures to use 

- https://github.com/mozilla/TTS
- https://github.com/ming024/FastSpeech2

**Comment by zaidalyafeai** [comment]
Here is a sample colab notebook of using fastspeech2 by Huu Nguyen 

https://colab.research.google.com/drive/1XPbG44o0oqmRgzdptMEe3gsosWzqPhdD?usp=sharing

**Comment by KhalidAlt** [comment]
I am interested in working with TTS and I would like to contribute in the project if possible.

**Comment by zaidalyafeai** [comment]
Hey @KhalidAlt, that is great. Do you have any experience with speech models?

**Comment by KhalidAlt** [comment]
> Do you have any experience with speech models?

No, but I have experience with NLP models such as transformer, bert, and GPT

**Comment by zaidalyafeai** [comment]
@KhalidAlt, that is actually good, because many recent speech models use transformer blocks. We are currently collecting some ideas to see how easy to fine-tune or possibly retrain some of the models in Arabic. As a start, maybe familiarize yourself with speech models, maybe run the notebook I shared.

**Comment by KhalidAlt** [comment]
@zaidalyafeai, OK that's great! I will look into speech models and the notebook.

**Comment by IslamMohamedMosaad** [comment]
Hey @zaidalyafeai, that's awesome and i am able to contribute here.

**Comment by zaidalyafeai** [comment]
Hey @IslamMohamedMosaad , that is awesome! Let us first search if there are any open source models for Arabic TTS.

**Comment by IslamMohamedMosaad** [comment]
Here is a [released model](https://github.com/youssefsharief/arabic-tacotron-tts) using **Tacotron** .

**Comment by zaidalyafeai** [comment]
@IslamMohamedMosaad that is a great start. We can use that as a baseline for moving forward.  We can also port the pretrained models here cc @youssefsharief.

**Comment by IslamMohamedMosaad** [comment]
@zaidalyafeai what about making n-issue for tasks ?!

**Comment by zaidalyafeai** [comment]
Hey Islam, I don't get your point ?

**Comment by zaidalyafeai** [comment]
Hey @IslamMohamedMosaad @KhalidAlt , I prepared a [notebook ](https://colab.research.google.com/drive/1DasQOG_WkkHM9ToAmp1A-sjzngZvP2Gn?usp=sharing)for training fastspeech2 on LJSpeech English data. Now, we need to convert that to run for Arabic data like https://arabicspeech.org/resources/ or http://en.arabicspeechcorpus.com/. The latter might be easier because it contains alignments.

**Comment by salah-zaiem** [comment]
Hello Zaid, 
When you say, Arabic TTS, you mean Modern Standard Arabic, or are you speaking about precise dialects ?

**Comment by zaidalyafeai** [comment]
Hey @salah-zaiem , we are tackling both.

**Comment by mehdihosseinimoghadam** [comment]
Hey everyone
Amazing to see you all working on TTS.
I have an start up in the field of Voice and NLP, and I would like to share my experience with you.
Just some questions to begin
1)Do you have sufficient amount of transcribed data? If yes how many hours?

> Note :
your data sould be in the right format as [LJSpeech](https://www.google.com/url?sa=t&source=web&rct=j&url=https://keithito.com/LJ-Speech-Dataset&ved=2ahUKEwiZ2quO0fjvAhUn_rsIHdVNDK0QFjAAegQIAxAC&usg=AOvVaw1BmcKo9h872WlPosTyGUqb)  dataset 

2)Is this work for enterprise purposes or just academic?

**Comment by zaidalyafeai** [comment]
Hey @mehdihosseinimoghadam, thanks for tuning in. 

1. [Arabic Speech Corpus](http://en.arabicspeechcorpus.com/) has around 1.8K wav files in a similar format to LJSpeech. We might have to modify the code to work with bulkwater if needed. There are other datasets that are much larger but don't contain any alignments. 
2. Academic. This work is open source and all the models will be avilable for the public.

**Comment by salah-zaiem** [comment]
I'd be interested in joining, I have some experience working on TTS, and I am an arabic speaker as well.

**Comment by zaidalyafeai** [comment]
Hey everyone. I created a fork of the fastspeech2 repo https://github.com/zaidalyafeai/FastSpeech2. I made some modifications to work on the Arabic speech corpus.

**Comment by zaidalyafeai** [comment]
We have a slack channel. If you want to be added let me know.
