### ISSUE TITLE
Transcriptions of longer audios

### ISSUE THREAD

**Issue by kruthikakr** [ARBML/klaam#7]
Hi

I tested for few longer audios , but transcpit is just a part of it..how to process for longer audios ?

**Comment by zaidalyafeai** [comment]
We have a maximum of 8 seconds for transcriptions. We allow longer files soon, for the time being maybe split the audio file and merge the predictions.

**Comment by kruthikakr** [comment]
Can VAD will solve the problem ? I am not sure for Arabic.  Any inputs to try this ?

**Comment by zaidalyafeai** [comment]
mmm haven't tried it before but I guess it should work for Arabic. Let me know if you want to contribute to the library by adding it!

**Comment by zaidalyafeai** [comment]
Closing for now. Feel free to reopen!
